excluded:
  - scripts
  - Carthage
  - certificates
  - PactConsumerSwiftTests/
  - Products/

included:
  - PactConsumerSwift/

force_cast:
  severity:
    warning # implicitly
force_try:
  severity: warning # explicitly

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50

identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - URL
    - url
    - GET
    - PUT
    - GlobalAPIKey

reporter: "xcode"
