name: Pull Request

env:
  PROJECT_NAME: "PactConsumerSwift.xcodeproj"

on: [pull_request, workflow_dispatch]

jobs:
  test_xcodebuild:
    name: Run tests
    runs-on: macOS-10.15

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactConsumerSwift iOS"
            destination: "platform=iOS Simulator,name=iPhone 12 Pro"
            carthage_platform: ios
          - scheme: "PactConsumerSwift macOS"
            destination: "arch=x86_64"
            carthage_platform: macos
          - scheme: "PactConsumerSwift tvOS"
            destination: "OS=14.2,name=Apple TV 4K (at 1080p)"
            carthage_platform: tvos

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}
      CARTHAGE_PLATFORM: ${{ matrix.carthage_platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: Carthage/build
          key: ${{ runner.os }}-pact-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-pact-
            ${{ runner.os }}-

      - name: Prepare the tools
        run: |
          scripts/install_deps.sh

      - name: "Run tests"
        run: |
          scripts/build.sh

  test_spm:
    name: Test for SPM
    runs-on: macOS-10.15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Swift build
        run: |
          swift build
          echo "⚠️  Skipping \"swift test\" as no test target is defined in \"Package.swift\" (https://github.com/DiUS/pact-consumer-swift/commit/229f35d63a547f492c7ba9e177ac8d7b685e7a7f)"

  test_carthage:
    name: "Test Carthage dependency"
    runs-on: macOS-10.15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: Carthage/build
          key: ${{ runner.os }}-pact-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-pact-
            ${{ runner.os }}-

      - name: Prepare Tools
        run: |
          scripts/install_deps.sh

      - name: Carthage build
        run: |
          scripts/carthage_xcode12 build --no-skip-current --platform "ios,macos,tvos"
